require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '12.0'

target 'SampleApp' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

target 'Rich Notification Extension' do
  pod 'Iterable-iOS-AppExtensions'
end
