version: "2"
exclude_patterns:
  # - ".*/"
  - "docs/"
  - "**/node_modules/"
  - "scripts/"
  - "**/__mocks__/"
  - "**/__tests__/"
  - "**/.*"
  - "**/*.config.js"
  - "**/*.h"
  - "**/*.json"
  - "**/*.lock"
  - "**/*.md"
  - "**/*.plist"
  - "**/*.podspec"
  - "**/*.xcodeproj"
  - "**/*.xcworkspace"
  - "**/*.yml"
  - "**/build.gradle"
  - "**/AndroidManifest.xml"
plugins:
  eslint:
    enabled: true
  editorconfig:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  shellcheck:
    enabled: true
  swiftlint:
    enabled: true
  tailor:
    enabled: true
  tslint:
    enabled: true
