# Tests should be moved here in the future.
version: 2.1

references:
  machine_config: &machine_config
    machine:
      image: default

  defaults: &defaults
    resource_class: large
    working_directory: ~/react-native-sdk
    docker:
      - image: cimg/node:20.10

orbs:
  node: circleci/node@6.3.0
  android: circleci/android@3.0.0
  rn: react-native-community/react-native@8.0.0
  ruby: circleci/ruby@2.2.1

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
workflows:
  build:
    jobs:
      - install