version: 2.1

references:
  machine_config: &machine_config
    machine:
      image: default

  defaults: &defaults
    resource_class: large
    working_directory: ~/react-native-sdk
    docker:
      - image: cimg/node:20.10

orbs:
  node: circleci/node@6.3.0
  android: circleci/android@3.0.0
  rn: react-native-community/react-native@8.0.0
  ruby: circleci/ruby@2.2.1

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - node/install:
          install-yarn: true
          yarn-version: 3.6.1
          node-version: '20.10.0'
      - restore_cache:
          # bump the version number to invalidate cache
          # and see below for another usage of this
          keys:
            - v3-yarn-packages-{{ checksum "yarn.lock" }}
            - v3-yarn-packages-
      - run: yarn install --network-concurrency 1 --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          # bump the version number to invalidate cache
          key: v3-yarn-packages-{{ checksum "yarn.lock" }}
      # Download and cache dependencies
      - run:
          name: Install example app dependencies
          command: |
            cd example
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: example-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - example/node_modules
      - run:
          name: Install ios-deploy, detox, react-native-cli
          command: npm install -g ios-deploy detox-cli react-native-cli
      - run:
          name: Install Applesimutils
          command: |
            brew tap wix/brew
            brew install applesimutils
      - run:
          name: Install pods
          command: |
            cd example/ios
            pod install
            cd ../..
      - persist_to_workspace:
          root: ~/react-native-sdk
          paths:
            - node_modules
            - example/node_modules
workflows:
  build:
    jobs:
      - install