name: Run Detox Tests
on: [pull_request]

jobs:
    build-and-test-ios:
        name: iOS - Build and run Detox tests
        runs-on: macos-13-xlarge

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc

            - name: Repo Yarn install
              run: yarn install

            - name: Example App Yarn install
              run: cd example && yarn install

            - name: Pod install
              run: cd example/ios && pod install

            - name: Build Detox
              run: yarn detox:ios:build

            - name: Start Metro Server
              run: yarn example detox:start &

            - name: Install Applesimutils
              run: |
                  brew tap wix/brew
                  brew install applesimutils

            - name: Run Detox tests
              run: yarn detox:ios:test:ci

            - name: Upload Test Artifact
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: detox-ios-artifacts
                  path: artifacts
                  retention-days: 5

    build-and-test-android:
        name: Android - Build and run Detox tests
        runs-on: ubuntu-latest

        steps:
            - name: Free Disk Space (Ubuntu)
              uses: jlumbroso/free-disk-space@main
              with:
                  tool-cache: true
                  android: false

            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: zulu
                  java-version: 17

            - name: Repo Yarn install
              run: yarn install

            - name: Example App Yarn install
              run: cd example && yarn install

            - name: Build Detox
              run: yarn detox:android:build

            - name: Start Metro Server
              run: yarn example detox:start &

            - name: Run Detox tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                  api-level: 31
                  arch: x86_64
                  avd-name: Android_API31
                  force-avd-creation: false
                  emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-metrics
                  disable-animations: false
                  script: yarn detox:android:test:ci

            - name: Upload Test Artifact
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                  name: detox-android-artifacts
                  path: artifacts
                  retention-days: 5