name: Integration Tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: 12.0

      - name: Install dependencies
        run: cd integration-testing/  && yarn install

      - name: pod install
        run: cd integration-testing/ios/ && pod install

      - name: Build and Test
        shell: bash
        env: 
          ITERABLE_API_KEY: ${{secrets.ITERABLE_API_KEY}}
          SEND_IN_APP_CAMPAIGN_ID: ${{secrets.SEND_IN_APP_CAMPAIGN_ID}}
          SKIP_IN_APP_CAMPAIGN_ID: ${{secrets.SKIP_IN_APP_CAMPAIGN_ID}}
          OPEN_DEEP_LINK_CAMPAIGN_ID: ${{secrets.OPEN_DEEP_LINK_CAMPAIGN_ID}}
          OPEN_SAFARI_CAMPAIGN_ID: ${{secrets.OPEN_SAFARI_CAMPAIGN_ID}}
          CUSTOM_ACTION_CAMPAIGN_ID: ${{secrets.CUSTOM_ACTION_CAMPAIGN_ID}}
        run: |
          ./integration-testing/ios/scripts/run_test.sh
