name: Integration Tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: '14.3.1'

      - name: Install app dependencies
        uses: ./.github/actions/setup

      - name: Install detox CLI
        run: npm install -g detox-cli

      - name: Install react native CLI
        run: npm install -g react-native-cli

      - name: Install Applesimutils
        run: |
            brew tap wix/brew
            brew install applesimutils

      - name: Install example app dependencies
        run: cd example; yarn install; cd -

      - name: pod install
        run: cd example/ios; pod install; cd -

      - name: List devices
        run: applesimutils --list

      - name: Start Metro Server
        run: yarn example detox:start &

      - name: Build and Test
        shell: bash
        env:
          ITBL_API_KEY: ${{secrets.ITERABLE_API_KEY}}
          ITBL_ID: ${{secrets.ITBL_ID}}
          SEND_IN_APP_CAMPAIGN_ID: ${{secrets.SEND_IN_APP_CAMPAIGN_ID}}
          SKIP_IN_APP_CAMPAIGN_ID: ${{secrets.SKIP_IN_APP_CAMPAIGN_ID}}
          OPEN_DEEP_LINK_CAMPAIGN_ID: ${{secrets.OPEN_DEEP_LINK_CAMPAIGN_ID}}
          OPEN_SAFARI_CAMPAIGN_ID: ${{secrets.OPEN_SAFARI_CAMPAIGN_ID}}
          CUSTOM_ACTION_CAMPAIGN_ID: ${{secrets.CUSTOM_ACTION_CAMPAIGN_ID}}
        run: cd example; yarn detox test --configuration ios.sim.debug; cd -

