name: Test & Publish code coverage
on: [pull_request]

# on:
#   push:
#     branches:
#       - "master"
#   pull_request:
#     branches:
#       - "**"

jobs:
  test-comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: |
          yarn test --coverage --coverageReporters json-summary

      - name: Test coverage comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          hide-comment: false
          coverage-summary-path: ./coverage/coverage-summary.json
        # uses: MartinNuc/codeclimate-action@2
        # env:
        #   CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        # with:
        #   coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
        # uses: paambaati/codeclimate-action@v9.0.0
        # env:
        #   CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        # with:
        #   coverageCommand: yarn test:coverage
        #   debug: true
        #   coverageLocations: |
        #     ${{github.workspace}}/coverage/*.lcov:lcov
  test-code-climate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: |
          yarn test --coverage --coverageReporters lcov

      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test --coverage --coverageReporters lcov
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
