name: Test & Publish code coverage
on: [pull_request]

# on:
#   push:
#     branches:
#       - "master"
#   pull_request:
#     branches:
#       - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test & publish code coverage
        uses: MartinNuc/codeclimate-action@2
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
        # uses: paambaati/codeclimate-action@v9.0.0
        # env:
        #   CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        # with:
        #   coverageCommand: yarn test:coverage
        #   debug: true
        #   coverageLocations: |
        #     ${{github.workspace}}/coverage/*.lcov:lcov
