name: Unit Tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

jobs:
  test-comment:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: |
          yarn test --coverage --coverageReporters json-summary

      - name: Test coverage comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          hide-comment: false
          coverage-summary-path: ./coverage/coverage-summary.json
          
run-tests-and-publish-coverage:
  name: Upload unit test results to qlty
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3

    - name: Setup
      uses: ./.github/actions/setup

    - name: Run tests
      run: |
        yarn test --coverage --coverageReporters lcov

    - name: Upload coverage to qlty
      uses: qltysh/qlty-action/coverage@v1
      with:
        token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        files: coverage/lcov.info
