name: Unit Tests

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "**"

jobs:
  test-comment:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: |
          yarn test --coverage --coverageReporters json-summary

      - name: Test coverage comment
        id: coverageComment
        uses: MishaKav/jest-coverage-comment@main
        with:
          hide-comment: false
          coverage-summary-path: ./coverage/coverage-summary.json
          
  run-tests-and-publish-coverage:
    name: Upload unit test results to qlty
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
  
      - name: Setup
        uses: ./.github/actions/setup
  
      - name: Run tests
        run: |
          yarn test --coverage --coverageReporters lcov
  
      - name: Upload coverage to qlty
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/lcov.info

  android-bridge-tests:
    name: Android bridge unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Finalize Android SDK
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('example/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Android bridge unit tests
        working-directory: example/android
        run: ./gradlew :iterable_react-native-sdk:testDebugUnitTest --no-daemon --console=plain
